package:
  name: gvasp
  version: 0.1.5.pre

source:
  path: .

build:
  entry_points:
    - gvasp = gvasp.main:main

requirements:
  build:
    - vs2019_win-64          # [win]
    - {{ compiler('c') }}    # [linux,osx]
    - {{ compiler('cxx') }}  # [linux,osx]

  host:
    - python
    - pybind11
    - numpy >=1.19
    - Cython
    - setuptools

  run:
    - python
    - numpy >=1.19
    - pybind11
    - Cython
    - lxml
    - matplotlib
    - pandas
    - pyyaml
    - scipy
    - pytest
    - seekpath

about:
  home: https://github.com/Rasic2/gvasp
  license: GPL3
