name: PyPI Package Build
on: push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保完整克隆，获取所有历史记录和标签
      - name: PyPI build steps
        uses: ./.github/actions/pypi-build
        with:
          CIBW_BUILD: "cp311-manylinux_x86_64 cp39-manylinux_x86_64"  # 添加了Python 3.11支持
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保完整克隆，获取所有历史记录和标签
      - name: PyPI build steps
        uses: ./.github/actions/pypi-build
        with:
          CIBW_BUILD: "cp311-macosx_arm64 cp39-macosx_arm64"
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保完整克隆，获取所有历史记录和标签
      - name: PyPI build steps
        uses: ./.github/actions/pypi-build
        with:
          CIBW_BUILD: "cp311-win_amd64 cp39-win_amd64"  # Windows平台的Python版本
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}